name: publish
on:
  push:
    tags:
      - "*.*.*"
      - "v*"

permissions:
  contents: read
  id-token: write   # нужно для OIDC

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -U build
      - run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
